### ISSUE TITLE
Would like to add support for bulk associations for win11!

### ISSUE THREAD

**Issue by sr79368142** [MehranAkbarii/DefaultProgramsRemake#1]
Dear MehranAkbarii, this tool you have developed has greatly facilitated the optimization of my win11 setup, but I would like to make a small suggestion to you, which I hope you will accept!
Could you add a batch association option for this application, when this option is checked, you can batch associate the same type of file format for the default application, which is very convenient for some software.
Considering that SetUserFTA itself is to support Win11 for the specified application batch association format and development, give up the batch association function of SetUserFTA, like losing its soul! This is very regrettable!
I hope you will give it some more thought!!!! Once again, I salute you and applaud your development work!!!!

**Comment by MehranAkbarii** [comment]
by using **Windows default app picker (openWith menu)** you can set any program **(.exe)** as default program for your target extension from anywhere in your PC, but yes I can Implement batch association for file types to set your default apps without using Windows default app picker and that will be a good alternative way for the users who set their Windows system language to a language other than English because Windows default app picker won't open for them when their double click on an extension

**Comment by sr79368142** [comment]
Dear MehranAkbarii, thank you for taking time to reply promptly.
I am extremely happy that my small request has been fulfilled.
Wish you a happy life!
Hope your work goes smoothly!

**Comment by MehranAkbarii** [comment]
> Dear MehranAkbarii, thank you for taking time to reply promptly. I am extremely happy that my small request has been fulfilled. Wish you a happy life! Hope your work goes smoothly!

Thanks
